name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Dependencies
        run: pnpm install

      - name: Rebuild Native Dependencies
        run: npx electron-builder install-app-deps

      - name: Build and Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pnpm run type-check
          pnpm run build:client
          if [ "$RUNNER_OS" == "macOS" ]; then
            npx electron-builder --mac --publish always
          elif [ "$RUNNER_OS" == "Windows" ]; then
            npx electron-builder --win --publish always
          fi
